### ISSUE TITLE
Add embedded language support for markdown in @docs and @moduledocs

### ISSUE THREAD

**Issue by Terbium-135** [lexical-lsp/vscode-lexical#87] opened 2024-12-10 08:04 UTC
Right now I am extracting the text into a markdown file, edit and copy back.

It would be very nice to get syntax highlighting for @doc and @moduledoc parts. Since these are markdown the readability might increase.

Instead of this:
![2024-12-10 09_02_23-user_login_live ex - ganymed  SSH_ Raspberry4  - Visual Studio Code - Insiders](https://github.com/user-attachments/assets/476b8a14-5af5-4f9e-a013-d95fb7a25bd0)

one might see:
![2024-12-10 09_01_42-doc md - ganymed  SSH_ Raspberry4  - Visual Studio Code - Insiders](https://github.com/user-attachments/assets/8936e957-18d7-43c9-8148-ed5c99588ffd)

**Comment by Blond11516** [comment] 2024-12-14 22:32
@Terbium-135 This should be fixed on main. Please pull the latest main and try it out when you get the chance. Thanks!

**Comment by lukaszsamson** [comment] 2024-12-15 20:41
@Blond11516 I tried that in ElixirLS v0.15 and had to revert as markdown rules would leak out of context and break highlighting of everything following. See https://github.com/elixir-lsp/vscode-elixir-ls/issues/315#issuecomment-1602086184

**Comment by Terbium-135** [comment] 2024-12-16 06:18
I tried it as well and facing:
![2024-12-16 06_07_55- Extension Development Host  core_components ex - Visual Studio Code - Insiders](https://github.com/user-attachments/assets/9263eb53-61d1-4fc4-8cf6-61ee73b9e853)

I changed package.json and set:
```
  "engines": {
    "vscode": "^1.79.0-insider"
  },
```

I see no leakage so far. But only had a quick glance.
![2024-12-16 06_42_49- Extension Development Host  core_components ex - Visual Studio Code - Insiders](https://github.com/user-attachments/assets/08941c1f-5cbf-42b2-83f3-02aa6c1822d0)

and

![2024-12-16 07_12_20- Extension Development Host  ● core_components ex - Visual Studio Code - Insider](https://github.com/user-attachments/assets/2122d2d0-d4fa-4ad4-9a59-6b2b53134fbe)

I am not using ElixirLS.

**Comment by Terbium-135** [comment] 2024-12-16 17:28
Sadly I discovered a file which leaks markdown - perhaps something can be done to better (start and) terminate the heredoc area?

![2024-12-16 18_23_16- Extension Development Host  authentication_component ex - Visual Studio Code - ](https://github.com/user-attachments/assets/450cf372-bb83-4a10-a59b-e45b5db0359e)

taken from this part:

![2024-12-16 18_24_53- Extension Development Host  authentication_component ex - Visual Studio Code - ](https://github.com/user-attachments/assets/a3d519ba-e176-4f30-8eca-727e9e97ad77)

The 2nd next `"""` ends markdown and switches back to elixir:


![2024-12-16 18_27_30- Extension Development Host  authentication_component ex - Visual Studio Code - ](https://github.com/user-attachments/assets/b5df6c98-5b36-4b46-9d91-813715aaa9c3)

**Comment by Blond11516** [comment] 2024-12-17 03:24
So from what I've seen the issue of leakage is caused by the additional indentation that `@doc` and friends add at the beginning of the markdown. This causes vscode to misinterpret the markdown as soon as it detects some sort of indented element ([non-fenced code block](https://www.markdownguide.org/basic-syntax/#code-blocks), [element within a list](https://www.markdownguide.org/basic-syntax/#adding-elements-in-lists), etc.)

For example, as soon as the heredoc contains a list, vscode interprets everything coming after it as a list element, because the markdown is indented as such:
![Capture d’écran 2024-12-16 220252](https://github.com/user-attachments/assets/8659cbdf-54bf-406e-8e5b-f9b89b6c9ec9)

This then appears to cause the next closing heredoc to be missed for whatever reason.

A custom markdown grammar might indeed be able to fix this, but that's obviously not a very desirable solution. I'll dig a bit into TextMate to see if there's any way to have it ignore this identation but I wouldn't bet on that being the case. Ideally I'd like to see how other extensions handle this; it would need to be a grammar that injects a whitespace-sensitive language (markdown, python, etc.) with some implicit indentation but I don't have any ideas off the top of my head. I'm all ears if anyone knows of something like this 🤷 

I've pushed a small [reproduction repository](https://github.com/Blond11516/markdown-leakage-repro) with examples of list and nested module failures.

**Comment by Blond11516** [comment] 2024-12-17 03:30
I've reverted the changes from main and pushed them back in a [new branch](https://github.com/lexical-lsp/vscode-lexical/pull/89).

**Comment by Terbium-135** [comment] 2024-12-17 05:29
Thank you for all your work and investigation so far!

**Comment by SteffenDE** [comment] 2024-12-18 17:50
I think a while pattern should do the trick, see https://github.com/elixir-lsp/vscode-elixir-ls/issues/315#issuecomment-2551931723.

Confirmed working (with ElixirLS) for the examples from https://github.com/Blond11516/markdown-leakage-repro

**Closed** 2024-12-25 18:46 UTC
